name: Lint And Test

on: workflow_call

jobs:
  lint-and-test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: ["18.17.1"]
        npm-version: ["9.6.7"]
        pnpm-version: ["8.6.10"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment
        uses: otedesco/gh-action-templates/.github/actions/setup-environment@main
        with:
          node-version: ${{ matrix.node-version }}
          npm-version: ${{ matrix.npm-version }}
          pnpm-version: ${{ matrix.pnpm-version }}
          os: ${{ matrix.os }}

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Running pnpm install --frozen-lockfile"
          pnpm install --frozen-lockfile

      - run: pnpm type:check

      - run: pnpm lint:check
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - run: pnpm test


      - uses: otedesco/gh-action-templates/.github/actions/notify-status@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
