name: Build & Release NodeJs Library

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

permissions: {}

jobs:
  release-packages:
    name: Build & Release package with the supported runtime
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Setup environment
        uses: otedesco/gh-action-templates/.github/actions/setup-environment@fde909e293173d95848d993528821a315e3b2059 # OPS-182 consumer compatibility fix
        with:
          registry-auth-required: "true"
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build package
        run: pnpm run build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@746c25e23caa47dceb6a48ee85b4cbc5a9f5f293 # v1.5.0
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
